name: main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.3.4
        with:
          required-ros-distributions: humble
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.2.6
        with:
          package-name: mh_amcl
          target-ros2-distro: humble
